# Generated by Django 4.0.4 on 2022-04-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='title',
        ),
    ]
