# Generated by Django 4.0.4 on 2022-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0002_remove_patient_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Домашний адрес'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страховая организация'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Электронная почта родителя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО родителя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='parent_number_phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер телефона родителя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='policy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страховое свидетельство'),
        ),
    ]
