# Generated by Django 4.0.4 on 2022-04-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0004_alter_patient_address_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questname', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('answerlet', models.CharField(max_length=100, verbose_name='Буквенный ответ')),
                ('answernum', models.IntegerField(max_length=100, verbose_name='Численный ответ')),
                ('answermulty', models.PositiveSmallIntegerField(choices=[(1, 'Да'), (2, 'Нет'), (3, 'Не знаю')], default=2, verbose_name='Множественный выбор')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
