# Generated by Django 4.0.4 on 2022-04-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0005_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answernum',
            field=models.IntegerField(verbose_name='Численный ответ'),
        ),
    ]
