# Generated by Django 4.0.4 on 2022-04-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0008_alter_patient_address_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='father_nation',
            field=models.CharField(choices=[('Русские', 'Русские'), ('Украинцы', 'Украинцы'), ('Немцы', 'Немцы'), ('Казахи', 'Казахи'), ('Белорусы', 'Белорусы'), ('Алтайцы', 'Алтайцы'), ('Кумандинцы', 'Кумандинцы'), ('Татары', 'Татары'), ('Другая', 'Другая')], default=1, max_length=10, verbose_name='Нация отца пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mother_nation',
            field=models.CharField(choices=[('Русские', 'Русские'), ('Украинцы', 'Украинцы'), ('Немцы', 'Немцы'), ('Казахи', 'Казахи'), ('Белорусы', 'Белорусы'), ('Алтайцы', 'Алтайцы'), ('Кумандинцы', 'Кумандинцы'), ('Татары', 'Татары'), ('Другая', 'Другая')], default=1, max_length=10, verbose_name='Нация матери пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nation',
            field=models.CharField(choices=[('Русские', 'Русские'), ('Украинцы', 'Украинцы'), ('Немцы', 'Немцы'), ('Казахи', 'Казахи'), ('Белорусы', 'Белорусы'), ('Алтайцы', 'Алтайцы'), ('Кумандинцы', 'Кумандинцы'), ('Татары', 'Татары'), ('Другая', 'Другая')], default=1, max_length=10, verbose_name='Нация пациента'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default=1, max_length=7, verbose_name='Пол пациента'),
        ),
    ]
