# Generated by Django 4.0.4 on 2022-04-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0011_alter_question_options_remove_question_answerlet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Выбор для вопросов',
                'verbose_name_plural': 'Выборы для вопросов',
            },
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Поле для выбора', 'verbose_name_plural': 'Поля для выборов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='Choices',
        ),
        migrations.AlterField(
            model_name='question',
            name='questname',
            field=models.CharField(max_length=100, verbose_name='Название вопроса'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.fields'),
        ),
    ]
