# Generated by Django 4.0.4 on 2022-04-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0013_alter_choice_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questchoices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.fields'),
        ),
    ]
