# Generated by Django 4.0.4 on 2022-04-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0014_question_questchoices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questchoices',
            new_name='fieldstest',
        ),
        migrations.AddField(
            model_name='choice',
            name='testing',
            field=models.ManyToManyField(through='amscapp.Question', to='amscapp.fields'),
        ),
        migrations.AddField(
            model_name='question',
            name='choicetest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='amscapp.fields'),
        ),
    ]
