# Generated by Django 4.0.4 on 2022-04-19 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0015_rename_questchoices_question_fieldstest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='testing',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choicetest',
        ),
    ]
