# Generated by Django 4.0.4 on 2022-04-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0016_remove_choice_testing_remove_question_choicetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации пациента'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.patient')),
                ('quest', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.question')),
            ],
            options={
                'verbose_name': 'Анкетирование',
                'verbose_name_plural': 'Анкетирования',
            },
        ),
    ]
