# Generated by Django 4.0.4 on 2022-05-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0017_alter_patient_registration_date_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Вариант ответа')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amscapp.fields')),
            ],
            options={
                'verbose_name': 'Поле для выбора',
                'verbose_name_plural': 'Поля для выборов',
            },
        ),
        migrations.AlterField(
            model_name='complaint',
            name='quest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.fields'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
