# Generated by Django 4.0.4 on 2022-05-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0018_option_alter_complaint_quest_delete_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
