# Generated by Django 4.0.4 on 2022-05-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amscapp', '0019_delete_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amscapp.patient')),
            ],
            options={
                'verbose_name': 'Анкетирование',
                'verbose_name_plural': 'Анкетирования',
            },
        ),
    ]
